[client_register]
command:/usr/local/opnsense/scripts/OPNsense/Usque/enrollment.py register
parameters:%s %s
type:script
message:Registering an usque egress client

[client_register_status]
command:/usr/local/opnsense/scripts/OPNsense/Usque/enrollment.py status
parameters:%s
type:script_output
message:Get usque client enrollment status

[client_registration_status]
command:/usr/local/opnsense/scripts/OPNsense/Usque/enrollment.py registration-status
parameters:%s
type:script_output
message:Get usque client registration state

[start]
command:/usr/local/etc/rc.d/usque onestart
parameters:
type:script_output
message:Starting usque tunnel instances

[stop]
command:/usr/local/etc/rc.d/usque onestop
parameters:
type:script_output
message:Stopping usque tunnel instances

[restart]
command:/usr/local/etc/rc.d/usque onerestart
parameters:
type:script_output
message:Restarting usque tunnel instances

[status]
command:/usr/local/etc/rc.d/usque onestatus
errors:no
parameters:
type:script_output
message:Requesting usque tunnel status
