[client_register]
command:/usr/local/opnsense/scripts/OPNsense/Usque/enrollment.py register-client
parameters:%s %s
type:script
message:Registering an usque egress client

[client_service_token_register]
command:/usr/local/opnsense/scripts/OPNsense/Usque/enrollment.py register-client-service-token
parameters:%s %s
type:script
message:Registering an usque egress client with Cloudflare Access Service Auth

[mesh_register]
command:/usr/local/opnsense/scripts/OPNsense/Usque/enrollment.py register-mesh
parameters:%s %s
type:script
message:Registering an usque Mesh node

[client_register_status]
command:/usr/local/opnsense/scripts/OPNsense/Usque/enrollment.py status
parameters:%s
type:script_output
message:Get usque client enrollment status

[client_registration_status]
command:/usr/local/opnsense/scripts/OPNsense/Usque/enrollment.py registration-status
parameters:%s %s
type:script_output
message:Get usque tunnel registration state

[delete_registration]
command:/usr/local/opnsense/scripts/OPNsense/Usque/enrollment.py delete-registration
parameters:%s %s
type:script_output
message:Delete a stopped usque tunnel registration

[start]
command:/usr/local/etc/rc.d/usque onestart
parameters:
type:script_output
message:Starting usque tunnel instances

[stop]
command:/usr/local/etc/rc.d/usque onestop
parameters:
type:script_output
message:Stopping usque tunnel instances

[restart]
command:/usr/local/etc/rc.d/usque onerestart
parameters:
type:script_output
message:Restarting usque tunnel instances

[status]
command:/usr/local/etc/rc.d/usque onestatus
errors:no
parameters:
type:script_output
message:Requesting usque tunnel status
