#!/bin/sh

# PROVIDE: usque
# REQUIRE: LOGIN netif routing
# KEYWORD: shutdown

. /etc/rc.subr

name="usque"
rcvar="usque_enable"
command="/usr/local/opnsense/scripts/OPNsense/Usque/service.py"
start_cmd="${command} start"
stop_cmd="${command} stop"
restart_cmd="${command} restart"
status_cmd="${command} status"

load_rc_config "${name}"
: ${usque_enable:="NO"}

run_rc_command "$1"
