###################################################################
# Local syslog-ng configuration filter definition [usque].
###################################################################
filter f_local_usque {
    program("^usque-tun[0-9]{1,3}$" type("pcre"));
};
