PLUGIN_NAME=		usque
PLUGIN_VERSION=		0.2
PLUGIN_REVISION=	3
PLUGIN_COMMENT=		Experimental usque MASQUE native TUN integration
PLUGIN_DEPENDS=		usque-nativetun
PLUGIN_MAINTAINER=	vampywiz17@users.noreply.github.com
PLUGIN_WWW=		https://github.com/vampywiz17/os-usque
PLUGIN_LICENSE=		BSD2CLAUSE

.include "../../Mk/plugins.mk"
